title: My Final Project
author: Ben Yu
email: byu2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
My 2020-21 AP Comp Sci A website project

# social links
twitter_username: Benjamin_Yu5
github_username:  ben14yu

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
